name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/checkout@v2
        with:
          repository: 'git@github.com:arietimmerman/iiqbin.git'
          ssh-key: ${{ secrets.KEY }}
          path: './binaries'
          lfs: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Ant
        run: ant